#!/bin/sh
failMsg() {
    printf "fatal: not a git repository (or any parent up to mount point \/)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."
    exit 1
}

CURRENT=$PWD
GIT="$(git rev-parse --git-dir 2> /dev/null)" || failMsg
GIT=$(cd "$GIT/.."; pwd)
cd $GIT
echo $([ -z ${CURRENT#$GIT} ] && echo $1 || echo ${CURRENT#$GIT}/$1) >> ./.gitignore
cd $CURRENT
